name: linting, testing, building

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build production project
        run: npm run build:prod

      - name: Lint TypeScript
        run: npm run lint:ts

      - name: Lint SCSS
        run: npm run lint:scss

      - name: Run unit tests
        run: npm run test:unit

      - name: Build Storybook
        run: npm run storybook:build

      - name: Serve Storybook in background
        run: npx http-server storybook-static -p 6006 &

      - name: Wait for Storybook to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: http://localhost:6006/iframe.html
          timeout: 30

      - name: Generate Backstop config
        run: npm run generate:ui

      - name: Run visual regression tests (Backstop)
        run: npm run test:ui

      - name: Prepare Backstop report for download
        if: always()
        run: |
          mkdir -p public
          cp -r backstop_data/html_report/* public/
          cp -r backstop_data/bitmaps_test public/
          cp -r backstop_data/bitmaps_reference public/
          sed -i 's|\.\./bitmaps_test/|bitmaps_test/|g' public/config.js || true
          sed -i 's|\.\./bitmaps_reference/|bitmaps_reference/|g' public/config.js || true

      - name: Upload Backstop report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backstop-report
          path: public
