name: linting, testing, building

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build production project
        run: npm run build:prod

      - name: Lint TypeScript
        run: npm run lint:ts

      - name: Lint SCSS
        run: npm run lint:scss

      - name: Run unit tests
        run: npm run test:unit

      - name: Build Storybook
        run: npm run storybook:build

      - name: Serve Storybook in background
        run: npx http-server storybook-static -p 6006 &

      - name: Wait for Storybook to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: http://localhost:6006/iframe.html
          timeout: 30

      - name: Generate Backstop config
        run: npm run generate:ui

      - name: Run visual regression tests (Backstop)
        run: npm run test:ui

      - name: Upload Backstop HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backstop-html-report
          path: backstop_data/html_report

      - name: Upload Backstop bitmaps
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backstop-bitmaps
          path: backstop_data/bitmaps_test

  deploy-backstop-report:
    needs: pipeline
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Backstop HTML report
        uses: actions/download-artifact@v4
        with:
          name: backstop-html-report
          path: public

      - name: Download Backstop bitmaps
        uses: actions/download-artifact@v4
        with:
          name: backstop-bitmaps
          path: public/bitmaps_test

      - name: Fix image paths in HTML report
        run: |
          sed -i 's|/bitmaps_test/|bitmaps_test/|g' public/index.html
          sed -i 's|/bitmaps_test/|bitmaps_test/|g' public/config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public

